### ISSUE TITLE
Angular 12 NG0303: Can't bind to 'ngLet' since it isn't a known property of 'ng-container'

### ISSUE THREAD

**Issue by lubos-bistak** [meeroslav/ng-helpers#22]
NG0303: Can't bind to 'ngLet' since it isn't a known property of 'ng-container'

```
<ng-container *ngLet="currentRoute$ | async as currentRoute">
...
</ng-container>
```

LetModule imported in module:
```
...
import {LetModule} from 'ng-helpers';
....

@NgModule({
    imports: [
        CommonModule,
        RouterModule,
        LetModule,
...
    ],
...
```

node: v12.22.1
npm: 6.14.12
angular:  12.0.4

Just for test, i copied code "https://github.com/meeroslav/ng-helpers/blob/master/projects/ng-helpers/src/lib/let/let.directive.ts" into our Angular 12 project, i worked.

"*media" directive works fine, could be problem with "ng" prefix ?

**Comment by meeroslav** [comment]
@lubos-bistak thank you for reporting the error. The bug is actually within the LetModule. I will publish a new fix soon.

**Comment by meeroslav** [comment]
Resolved by https://github.com/meeroslav/ng-helpers/commit/e09ed11d162dbef385f12a4e9e4f36f17903a018
